spring:
  application:
    name: web_crafter_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_crafter
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: gbjy8347@gmail.com
    password: kouiwmojuknqerwu
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true        
  config:
    import: optional:classpath:ai.yml
server:
  port: 8080
#  servlet:
#    context-path: /test
mybatis:
  # XML 매퍼 파일들이 있는 경로를 지정합니다.
  mapper-locations: classpath:mapper/**/*.xml
  # DB의 snake_case(user_id)를 Java의 camelCase(userId)로 자동 변환해줍니다.
  configuration:
    map-underscore-to-camel-case: true
    # 콘솔에서 실제 실행되는 SQL을 보고 싶다면 아래 설정을 켭니다.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
